---
# http://docs.ansible.com/ansible/latest/set_fact_module.html
- name: Merge logstash_default and logstash variables
  set_fact:
    logstash_combined: "{{ logstash_defaults | combine(logstash, recursive=True) }}"

# Include OS-specific installation tasks.
- include_tasks: setup-RedHat.yml
  when:
    - ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when:
    - ansible_os_family == 'Debian'



# http://docs.ansible.com/ansible/latest/systemd_module.html
- name: Ensure logstash auto-starts
  systemd:
    name: logstash
    enabled: yes

# http://docs.ansible.com/ansible/latest/template_module.html
- name: Copy config file, input
  template:
    src: "{{ logstash_combined.input_conf }}"
    dest: "{{ logstash_combined.config_include_dir }}/10-input.conf"
    owner: root
    group: root
    mode: 0644
  when:
    - not logstash_combined.install_only

# http://docs.ansible.com/ansible/latest/template_module.html
- name: Copy config file, filter
  template:
    src: "{{ logstash_combined.filter_conf }}"
    dest: "{{ logstash_combined.config_include_dir }}/20-filter.conf"
    owner: root
    group: root
    mode: 0644
  when:
    - not logstash_combined.install_only

# http://docs.ansible.com/ansible/latest/template_module.html
- name: Copy config file, output
  template:
    src: "{{ logstash_combined.output_conf }}"
    dest: "{{ logstash_combined.config_include_dir }}/30-output.conf"
    owner: root
    group: root
    mode: 0644
  when:
    - not logstash_combined.install_only

# https://www.elastic.co/guide/en/logstash/latest/working-with-plugins.html
- name: Install plugins
  command: /usr/share/logstash/bin/logstash-plugin install {{ item }}
  loop: "{{ logstash_combined.install_plugins }}"
  when:
    - logstash_combined.install_plugins

# - name: Update logstash input plugins
# /usr/share/logstash/bin/logstash-plugin update logstash-input-beats

- name: Restart Logstash
  systemd:
    name: "{{ logstash_combined.daemon }}"
    state: restarted
  when:
    - not logstash_combined.install_only

- name: Wait for Logstash to become available
  wait_for:
    port: 5044
    delay: 5
  when:
    - not logstash_combined.install_only
